// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IntermediateProduct 上一步产物的传递信息（多步反应继承用）。
 */
export interface IntermediateProduct {
    "name": string;
    "molWeight": number;

    /**
     * 单位成本（元/kg）
     */
    "unitCost": number;

    /**
     * 实际产量（kg）
     */
    "actualYield": number;
}

/**
 * ProductResult 单个产物的计算结果。
 */
export interface ProductResult {
    /**
     * 理论产量（kg）
     */
    "theoreticalYieldKg": number;

    /**
     * 实际产量（kg）：输入或由收率推算
     */
    "actualYieldKg": number;

    /**
     * 重量收率（%）
     */
    "weightYield": number;

    /**
     * 摩尔收率（%）
     */
    "molarYield": number;

    /**
     * 单位成本（元/kg）= 本步总成本 ÷ 实际产量
     */
    "unitCost": number;

    /**
     * 是否主产物（供下一步继承）
     */
    "isPrimary": boolean;

    /**
     * 阻塞性错误
     */
    "blockingErrors": string[] | null;

    /**
     * 非阻塞警告
     */
    "warnings": string[] | null;
}

/**
 * ReagentResult 单个原料的计算结果。
 */
export interface ReagentResult {
    /**
     * 有效摩尔数（mol）
     */
    "moles": number;

    /**
     * 当量（计算或输入）
     */
    "equiv": number;

    /**
     * 理论投料量（kg）= 摩尔×分子量÷(含量%×1000)
     */
    "theoreticalAmountKg": number;

    /**
     * 实际投料量（kg）：输入或由当量推算
     */
    "actualAmountKg": number;

    /**
     * 单价（元/kg）
     */
    "unitPrice": number;

    /**
     * 成本（元）= 实际投料量×单价×(1-回收率%)
     */
    "cost": number;

    /**
     * 单位成本（元/kg）= 本原料成本 ÷ 本步主产物实际产量。
     * 无主产物或产量为 0 时为 0（此时成本仍可由 Cost 得到）。
     */
    "unitCost": number;

    /**
     * 阻塞性错误（如 当量与投料量都为空）
     */
    "blockingErrors": string[] | null;

    /**
     * 非阻塞警告
     */
    "warnings": string[] | null;
}

/**
 * StepResult 一步反应的完整计算结果。
 */
export interface StepResult {
    /**
     * 本步总成本（元）
     */
    "totalCost": number;

    /**
     * 底物有效摩尔数（mol）
     */
    "substrateMoles": number;

    /**
     * 各原料结果（与输入顺序一致）
     */
    "reagents": ReagentResult[] | null;

    /**
     * 各产物结果（与输入顺序一致）
     */
    "products": ProductResult[] | null;

    /**
     * 阻塞性错误（参数校验失败）
     */
    "blockingErrors": string[] | null;

    /**
     * 非阻塞警告
     */
    "warnings": string[] | null;

    /**
     * 主产物（供下一步继承），无主产物或计算失败时为 nil
     */
    "primaryProduct"?: IntermediateProduct | null;
}
