// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClearAllResult 清空物料库的结果（删除条数）。
 */
export interface ClearAllResult {
    "materialsDeleted": number;
    "pricesDeleted": number;
}
