// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CalculateInput 计算请求。
 */
export interface CalculateInput {
    "steps": models$0.ReactionStep[] | null;
}

/**
 * CalculateResult 计算结果。
 */
export interface CalculateResult {
    "steps": (engine$0.StepResult | null)[] | null;

    /**
     * 总成本（元）= 各步总成本之和
     */
    "totalCost": number;

    /**
     * 总产量（kg）= 最后一步主产物实际产量
     */
    "totalYieldKg": number;

    /**
     * 总单位成本（元/kg）= 总成本 ÷ 总产量
     */
    "totalUnitCost": number;
}

/**
 * ImportResult 导入结果。
 */
export interface ImportResult {
    /**
     * 导入的物料数
     */
    "materialsImported": number;

    /**
     * 更新的物料数（CAS 已存在）
     */
    "materialsUpdated": number;

    /**
     * 导入的价格记录数
     */
    "pricesImported": number;

    /**
     * 跳过的行（缺少 CAS）
     */
    "skipped": number;

    /**
     * 解析错误
     */
    "errors": string[] | null;
}

/**
 * MaterialPriceOption 物料可选价格下拉项。
 */
export interface MaterialPriceOption {
    "priceId": number;
    "materialId": number;
    "price": number;
    "unit": string;
    "pricePerKg": number;
    "supplier": string;
    "date": string;
    "spec": string;
    "content": number;
}

/**
 * SchemeExportFile 方案导出文件。
 * 
 * 导出内容是自足的：每行原料都带名称/分子式/分子量/含量/回收率以及价格快照，
 * 不含任何物料库或价格库的 id（materialId 会被清空）。因此导出文件可直接
 * 在另一台机器导入使用，无需目标机器存在同名物料，也不需要任何重连匹配。
 */
export interface SchemeExportFile {
    "version": number;
    "app": string;
    "exportedAt": string;
    "schemes": (models$0.Scheme | null)[] | null;
}

/**
 * SchemeImportResult 方案导入结果。
 */
export interface SchemeImportResult {
    "imported": number;
    "errors": string[] | null;
}

/**
 * SchemeSummary 方案列表项：方案元信息 + 由内联计算得出的结果摘要。
 * 
 * 列表页只关心「哪个方案、最终产物叫什么、单位成本多少」，
 * 不需要每个方案完整的 steps（那是载入时才拉的数据）；顺带省掉把全部
 * steps 序列化传给前端的开销。
 */
export interface SchemeSummary {
    "id": number;
    "name": string;
    "note": string;
    "stepCount": number;
    "createdAt": string;
    "updatedAt": string;

    /**
     * HasResult 是否算出了结果。false 时列表显示「-」，
     * 具体原因见 BlockingErrors / Errors。
     */
    "hasResult": boolean;

    /**
     * ProductName 最终产物名（最后一步主产物的名称）
     */
    "productName": string;

    /**
     * UnitCost 最终产物单位成本（元/kg）= 总成本 ÷ 总产量
     */
    "unitCost": number;

    /**
     * TotalCost 总成本（元）
     */
    "totalCost": number;

    /**
     * TotalYieldKg 总产量（kg）
     */
    "totalYieldKg": number;

    /**
     * BlockingErrors 计算被阻塞的原因（如「底物缺少分子量」「底物投料量需大于 0」）
     */
    "blockingErrors": string[] | null;

    /**
     * Errors 计算本身失败时的原因（与 BlockingErrors 区分：这是服务层错误）
     */
    "errors": string[] | null;
}
