// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReactionService 反应成本计算服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Calculate 执行反应成本计算。
 * 
 * 纯函数：完全不读物料库/价格库。方案自带全部输入（含价格快照），
 * 因此换机器、清空物料库都不影响已保存方案的计算结果。
 */
export function Calculate(input: $models.CalculateInput): $CancellablePromise<$models.CalculateResult | null> {
    return $Call.ByID(3415247734, input);
}

/**
 * FormatMoney 暴露给前端格式化金额。
 */
export function FormatMoney(v: number): $CancellablePromise<string> {
    return $Call.ByID(741710839, v);
}

/**
 * PriceOptionsForMaterial 返回某物料的价格选项（供前端下拉选择）。
 * 
 * 这是「物料库仅作为查询来源」的入口：只在用户选物料/刷新价格/比对价格变动时调用，
 * 计算路径完全不经过这里。
 * 返回列表按报价日期倒序，因此 out[0] 即该物料在库中的最新价——
 * 前端据此与方案自带的价格快照比对（差异阈值见前端 PRICE_DRIFT_THRESHOLD）。
 * 物料已不在库中时返回空列表而不是报错。
 */
export function PriceOptionsForMaterial(materialID: number): $CancellablePromise<$models.MaterialPriceOption[] | null> {
    return $Call.ByID(1885373859, materialID);
}
