// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReactionService 反应成本计算服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Calculate 执行反应成本计算。
 * 
 * 纯函数：完全不读物料库/价格库。方案自带全部输入（含价格快照），
 * 因此换机器、清空物料库都不影响已保存方案的计算结果。
 */
export function Calculate(input: $models.CalculateInput): $CancellablePromise<$models.CalculateResult | null> {
    return $Call.ByID(3415247734, input);
}

/**
 * DeleteScheme 删除方案。
 */
export function DeleteScheme(id: number): $CancellablePromise<void> {
    return $Call.ByID(783483566, id);
}

/**
 * ExportSchemes 导出选中方案为 SchemeExportFile（纯函数，便于测试）。
 */
export function ExportSchemes(ids: number[] | null): $CancellablePromise<$models.SchemeExportFile | null> {
    return $Call.ByID(1256995440, ids);
}

/**
 * ExportSchemesToFile 将选中的方案导出为 JSON 文件，弹出保存对话框写入磁盘。
 * ids 为空表示导出全部方案。返回保存的文件路径（用户取消时为空字符串）。
 * 桌面 WebView 不支持前端 a[download] 下载，因此由后端完成文件保存。
 */
export function ExportSchemesToFile(ids: number[] | null): $CancellablePromise<string> {
    return $Call.ByID(4250726943, ids);
}

/**
 * FormatMoney 暴露给前端格式化金额。
 */
export function FormatMoney(v: number): $CancellablePromise<string> {
    return $Call.ByID(741710839, v);
}

/**
 * GetScheme 获取单个方案。
 */
export function GetScheme(id: number): $CancellablePromise<models$0.Scheme | null> {
    return $Call.ByID(3184332985, id);
}

/**
 * ImportSchemes 解析 JSON 内容并导入方案（name 为空或 steps 为空的方案跳过）。
 * 
 * 导入文件是自足的，不需要在目标库中解析或重连物料：materialId 一律清空，
 * 计算直接用文件内的快照。这样跨机器导入不会出现 id 错指（静默算错钱）。
 */
export function ImportSchemes(data: string | null): $CancellablePromise<$models.SchemeImportResult | null> {
    return $Call.ByID(2662591393, data);
}

/**
 * ImportSchemesFromFile 弹出打开对话框选择 JSON 文件并导入方案。
 * 返回导入结果与出现的问题（文件为空或无方案时返回错误）。
 */
export function ImportSchemesFromFile(): $CancellablePromise<$models.SchemeImportResult | null> {
    return $Call.ByID(3246473823);
}

/**
 * ListSchemes 方案列表。
 */
export function ListSchemes(): $CancellablePromise<(models$0.Scheme | null)[] | null> {
    return $Call.ByID(2765576286);
}

/**
 * PriceOptionsForMaterial 返回某物料的价格选项（供前端下拉选择）。
 * 
 * 这是「物料库仅作为查询来源」的入口：只在用户选物料/刷新价格/比对价格变动时调用，
 * 计算路径完全不经过这里。
 * 返回列表按报价日期倒序，因此 out[0] 即该物料在库中的最新价——
 * 前端据此与方案自带的价格快照比对（差异阈值见前端 PRICE_DRIFT_THRESHOLD）。
 * 物料已不在库中时返回空列表而不是报错。
 */
export function PriceOptionsForMaterial(materialID: number): $CancellablePromise<$models.MaterialPriceOption[] | null> {
    return $Call.ByID(1885373859, materialID);
}

/**
 * SaveScheme 保存方案（id 为 0 时新增）。
 */
export function SaveScheme(sch: models$0.Scheme | null): $CancellablePromise<models$0.Scheme | null> {
    return $Call.ByID(3985361040, sch);
}
