// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SchemeService 方案管理服务：方案 CRUD 与 JSON 导入 / 导出。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateScheme 只新增、绝不更新已有行（id 一律忽略）。
 * 
 * 「另存为」走这条路径而不是 SaveScheme：后者 id > 0 时是整行更新，
 * 万一前端传错 id 就会把原方案悄悄覆盖掉。另存为的语义是「一定产生新行」，
 * 用这个接口能在服务端把这条语义钉死，不依赖调用方传对 id。
 */
export function CreateScheme(sch: models$0.Scheme | null): $CancellablePromise<models$0.Scheme | null> {
    return $Call.ByID(2108796309, sch);
}

/**
 * DeleteScheme 删除方案。
 */
export function DeleteScheme(id: number): $CancellablePromise<void> {
    return $Call.ByID(1364122082, id);
}

/**
 * ExportSchemes 导出选中方案为 SchemeExportFile（纯函数，便于测试）。
 */
export function ExportSchemes(ids: number[] | null): $CancellablePromise<$models.SchemeExportFile | null> {
    return $Call.ByID(3745946276, ids);
}

/**
 * ExportSchemesToFile 将选中的方案导出为 JSON 文件，弹出保存对话框写入磁盘。
 * ids 为空表示导出全部方案。返回保存的文件路径（用户取消时为空字符串）。
 * 桌面 WebView 不支持前端 a[download] 下载，因此由后端完成文件保存。
 */
export function ExportSchemesToFile(ids: number[] | null): $CancellablePromise<string> {
    return $Call.ByID(2632476523, ids);
}

/**
 * GetScheme 获取单个方案。
 */
export function GetScheme(id: number): $CancellablePromise<models$0.Scheme | null> {
    return $Call.ByID(3901300093, id);
}

/**
 * ImportSchemes 解析 JSON 内容并导入方案（name 为空或 steps 为空的方案跳过）。
 * 
 * 导入文件是自足的，不需要在目标库中解析或重连物料：materialId 一律清空，
 * 计算直接用文件内的快照。这样跨机器导入不会出现 id 错指（静默算错钱）。
 */
export function ImportSchemes(data: string | null): $CancellablePromise<$models.SchemeImportResult | null> {
    return $Call.ByID(1796718693, data);
}

/**
 * ImportSchemesFromFile 弹出打开对话框选择 JSON 文件并导入方案。
 * 返回导入结果与出现的问题（文件为空或无方案时返回错误）。
 */
export function ImportSchemesFromFile(): $CancellablePromise<$models.SchemeImportResult | null> {
    return $Call.ByID(2095023507);
}

/**
 * ListSchemes 方案列表（含结果摘要）。
 * 
 * 方案只持久化输入、不存计算结果，因此这里对每个方案跑一次纯函数计算取摘要。
 * 这样结果永远与方案内容一致，不会出现「改了方案但列表还是旧单价」的陈旧数据。
 * 计算失败不影响列表本身：原因写进摘要，列表照常返回。
 */
export function ListSchemes(): $CancellablePromise<($models.SchemeSummary | null)[] | null> {
    return $Call.ByID(3819372074);
}

/**
 * RenameScheme 只改方案名称（顺带保留备注），不刷新 updated_at。
 * 
 * 有意不复用 SaveScheme：那条路径是「整行更新 + 刷新 updated_at」，
 * 适合从编辑器保存完整方案，但改名只需要动名称。这样既避免前端为了
 * 改名把整行（含 steps 与 base64 附图，可能几 MB）拉回来再写回去，
 * 也让 updated_at / 列表排序保持「内容最后变更」的语义。
 */
export function RenameScheme(id: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2769981747, id, name);
}

/**
 * SaveScheme 保存方案（id 为 0 时新增）。
 */
export function SaveScheme(sch: models$0.Scheme | null): $CancellablePromise<models$0.Scheme | null> {
    return $Call.ByID(3738799316, sch);
}
