// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CalculateInput 计算请求。
 */
export interface CalculateInput {
    "steps": models$0.ReactionStep[] | null;
}

/**
 * ImportResult 导入结果。
 */
export interface ImportResult {
    /**
     * 导入的物料数
     */
    "materialsImported": number;

    /**
     * 更新的物料数（CAS 已存在）
     */
    "materialsUpdated": number;

    /**
     * 导入的价格记录数
     */
    "pricesImported": number;

    /**
     * 跳过的行（缺少 CAS）
     */
    "skipped": number;

    /**
     * 解析错误
     */
    "errors": string[] | null;
}

/**
 * MaterialPriceOption 物料可选价格下拉项。
 */
export interface MaterialPriceOption {
    "priceId": number;
    "materialId": number;
    "price": number;
    "unit": string;
    "pricePerKg": number;
    "supplier": string;
    "date": string;
    "spec": string;
    "content": number;
}
