// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReactionService 反应成本计算服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Calculate 执行反应成本计算。计算前会自动：
 *  1. 为每个原料从物料库填充名称/分子量/含量/回收率等信息
 *  2. 将所选价格记录（或最新价格）换算为 元/kg 单价
 */
export function Calculate(input: $models.CalculateInput): $CancellablePromise<engine$0.MultiStepResult | null> {
    return $Call.ByID(3244114891, input);
}

/**
 * DeleteScheme 删除方案。
 */
export function DeleteScheme(id: number): $CancellablePromise<void> {
    return $Call.ByID(3670791277, id);
}

/**
 * FormatMoney 暴露给前端格式化金额。
 */
export function FormatMoney(v: number): $CancellablePromise<string> {
    return $Call.ByID(1443244158, v);
}

/**
 * GetScheme 获取单个方案。
 */
export function GetScheme(id: number): $CancellablePromise<models$0.Scheme | null> {
    return $Call.ByID(1733746088, id);
}

/**
 * ListSchemes 方案列表。
 */
export function ListSchemes(): $CancellablePromise<(models$0.Scheme | null)[] | null> {
    return $Call.ByID(535480459);
}

/**
 * PriceOptionsForMaterial 返回某物料的价格选项（供前端下拉选择）。
 */
export function PriceOptionsForMaterial(materialID: number): $CancellablePromise<$models.MaterialPriceOption[] | null> {
    return $Call.ByID(3841289918, materialID);
}

/**
 * SaveScheme 保存方案（id 为 0 时新增）。
 */
export function SaveScheme(sch: models$0.Scheme | null): $CancellablePromise<models$0.Scheme | null> {
    return $Call.ByID(895005811, sch);
}
