// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Material 物料（化合物）
 */
export interface Material {
    "id": number;

    /**
     * 编码
     */
    "code": string;
    "name": string;
    "cas": string;

    /**
     * 化学式
     */
    "formula": string;

    /**
     * 分子量
     */
    "molWeight": number;

    /**
     * 含量(%)
     */
    "content": number;

    /**
     * 回收率(%)
     */
    "recoveryRate": number;
    "note": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * 便捷视图：物料 + 当前价格（最新一条）
 */
export interface MaterialWithPrice {
    "id": number;

    /**
     * 编码
     */
    "code": string;
    "name": string;
    "cas": string;

    /**
     * 化学式
     */
    "formula": string;

    /**
     * 分子量
     */
    "molWeight": number;

    /**
     * 含量(%)
     */
    "content": number;

    /**
     * 回收率(%)
     */
    "recoveryRate": number;
    "note": string;
    "createdAt": string;
    "updatedAt": string;
    "price": number;
    "priceUnit": string;
    "supplier": string;
    "priceDate": string;
    "priceCount": number;
}

/**
 * Price 价格记录
 */
export interface Price {
    "id": number;
    "materialId": number;

    /**
     * 价格数值（按 Unit 的单价）
     */
    "price": number;

    /**
     * 元/g | 元/mol | 元/kg
     */
    "unit": string;

    /**
     * 供应商
     */
    "supplier": string;

    /**
     * 日期（取最新）
     */
    "date": string;

    /**
     * 规格
     */
    "spec": string;

    /**
     * 含量(%)
     */
    "content": number;
    "note": string;
    "createdAt": string;
}

/**
 * ProductInput 一步反应中的一个产物
 */
export interface ProductInput {
    "materialId": number;
    "inherited": boolean;
    "name": string;
    "cas": string;
    "formula": string;
    "molWeight": number;

    /**
     * 标记主产物
     */
    "isSubstrate": boolean;

    /**
     * 计量数
     */
    "molarRatio": number;

    /**
     * 重量收率(%)
     */
    "weightYield": number | null;

    /**
     * 摩尔收率(%)
     */
    "molarYield": number | null;

    /**
     * 实际产量(kg)
     */
    "actualYield": number | null;
}

/**
 * ReactionStep 反应方案中的一步
 */
export interface ReactionStep {
    "id": number;
    "stepNum": number;

    /**
     * 步骤名称（可选）
     */
    "name": string;
    "reagents": ReagentInput[] | null;
    "products": ProductInput[] | null;
}

/**
 * ReagentInput 一步反应中的一个原料（输入）
 */
export interface ReagentInput {
    /**
     * 0 表示继承的中间产物
     */
    "materialId": number;

    /**
     * 是否继承自上一步产物
     */
    "inherited": boolean;
    "name": string;
    "cas": string;
    "formula": string;
    "molWeight": number;

    /**
     * 含量(%)
     */
    "content": number;

    /**
     * 回收率(%)
     */
    "recoveryRate": number;

    /**
     * 是否底物(基准 1 eq)
     */
    "isSubstrate": boolean;

    /**
     * 当量（可为空）
     */
    "equiv": number | null;

    /**
     * 实际投料量(kg)（可为空）
     */
    "amountKg": number | null;

    /**
     * 单价(元/kg)（可为空，多价格时由前端选择）
     */
    "unitPriceYuanPerKg": number | null;

    /**
     * 选中的价格记录 id（0 自动取最新）
     */
    "priceSourceId": number;
}

/**
 * Scheme 方案
 */
export interface Scheme {
    "id": number;
    "name": string;
    "note": string;
    "steps": ReactionStep[] | null;
    "createdAt": string;
    "updatedAt": string;
}
